version: '3'
services:
    backend:
        image: node:14.8.0-alpine3.10
        build: ./server
        container_name: 'backend'
        depends_on:
            - database
        ports:
            - '3000:3000'
        networks:
            - marcketplace_network
    database:
        image: mongo
        container_name: 'mongodb'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=marketplaceadmin
            - MONGO_INITDB_ROOT_PASSWORD=marketplace123
            - MONGO_INITDB_DATABASE=marketplace
        volumes:
            - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
            - ./mongo-volume:/data/db
        networks:
        - marcketplace_network
networks:
    marcketplace_network:
        driver: bridge
